name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          bash build.sh venc
          cp -Tr build/Release/bin output
          bash build.sh vdec
          cp -Tr build/Release/bin output

      - name: Sample
        run: |
          sudo apt-get update
          sudo apt-get install musl-dev
          x86_64-linux-musl-gcc x86/vdec-i386.c -o vdec-i386 -s -static

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            output/venc
            output/vdec
            vdec-i386
